const JOB = {
    location: [
        { name: "In person" },
        { name: "Remote" },
        { name: "On the road" },
    ],
    schedule: [
        { name: "4x12" },
        { name: "5x8" },
        { name: "Monday to Friday" },
        { name: "Day shift" },
        { name: "Night shift" },
        { name: "Evening shift" },
        { name: "No nights" },
        { name: "Overnight shift" },
        { name: "Weekend availability" },
        { name: "Weekends only" },
        { name: "No weekends" },
        { name: "On call" },
        { name: "Holidays" },
        { name: "Self-determined schedule" },
        { name: "After school" },
        { name: "Overtime" },
        { name: "Other" },
    ],
    type: [
        { name: "Full-time" },
        { name: "Part-time" },
        { name: "Contract" },
        { name: "Temporary" },
        { name: "Internship" },
    ],
    size: [
        { name: "1" },
        { name: "2" },
        { name: "3" },
        { name: "4" },
        { name: "5" },
        { name: "6" },
        { name: "7" },
        { name: "8" },
        { name: "9" },
        { name: "10" },
        { name: "10+" },
        { name: "I have an ongoing need to fill this role" },
    ],
    delay: [
        { name: "1 to 3 days" },
        { name: "3 to 7 days" },
        { name: "1 to 2 weeks" },
        { name: "2 to 4 weeks" },
        { name: "More than 4 weeks" },
    ],
    payBy: [
        { name: "Range" },
        { name: "Starting amount" },
        { name: "Maximum amount" },
        { name: "Exact amount" },
    ],
    supplemental: [
        { name: "Signing bonus" },
        { name: "Commission pay" },
        { name: "Bonus pay" },
        { name: "Tips" },
        { name: "Other" },
    ],
    submitResume: [{ name: "Yes" }, { name: "No" }, { name: "Optional" }],
    benefits: [
        { name: "Health insurance" },
        { name: "Paid time off" },
        { name: "Dental insurance" },
        { name: "401(k)" },
        { name: "Vision insurance" },
        { name: "Flexible schedule" },
        { name: "Tuition reimbursement" },
        { name: "Life insurance" },
        { name: "401(k) matching" },
        { name: "Retirement plan" },
        { name: "Referral program" },
        { name: "Employee discount" },
        { name: "Flexible spending account" },
        { name: "Health savings account" },
        { name: "Relocation assistance" },
        { name: "Parental leave" },
        { name: "Professional development assistance" },
        { name: "Employee assistance program" },
        { name: "Other" },
    ],
    qualifications: [
        {
            name: "Education",
            values: [
                { name: "High school or equivalent" },
                { name: "Associate" },
                { name: "Bachelor's" },
                { name: "Master's" },
                { name: "Doctorate" },
            ],
        },
        {
            name: "Experience",
            values: [
                { name: "1 year" },
                { name: "2 years" },
                { name: "3 years" },
                { name: "4 years" },
                { name: "5 years" },
                { name: "6 years" },
                { name: "7 years" },
                { name: "8 years" },
                { name: "9 years" },
                { name: "10 years" },
            ],
        },
        {
            name: "Interview Ability",
            values: [],
        },
        {
            name: "Security clearance",
            values: [
                { name: "Confidential" },
                { name: "Secret" },
                { name: "Top Secret" },
            ],
        },
        {
            name: "Shift Availability",
            values: [
                { name: "Day Shift" },
                { name: "Night Shift" },
                { name: "Overnight Shift" },
            ],
        },
        {
            name: "Skills test",
            values: [
                { name: "Attention to detail" },
                { name: "Software developer fit" },
                { name: "Work style: Conscientiousness" },
                { name: "Analyzing data" },
                { name: "Learning agility" },
                { name: "Work motivation" },
                { name: "Graphic design" },
                { name: "Work style: Reliability" },
                { name: "Customer focus & orientation" },
                { name: "Management & leadership skills: Impact & influence" },
                { name: "Proofreading" },
                { name: "Written communication" },
                { name: "Technical support: Customer situations" },
                { name: "Sales skills" },
                { name: "Verbal communication" },
                { name: "Technical support" },
                { name: "Teamwork: Interpersonal skills" },
                { name: "Typing" },
            ],
        },
        {
            name: "Willingness to travel",
            values: [
                { name: "25%" },
                { name: "50%" },
                { name: "75%" },
                { name: "100%" },
            ],
        },
        {
            name: "Work authorization",
            values: [],
        },
        {
            name: "Create custom question",
            values: [],
        },
    ],
}

export default JOB
