import { v4 as uuid } from "uuid"
const JOB = {
    payRate: [
        { id: uuid(), name: "Range" },
        { id: uuid(), name: "Starting amount" },
        { id: uuid(), name: "Maximum amount" },
        { id: uuid(), name: "Exact amount" },
    ],
    rate: [
        { id: uuid(), name: "per hour" },
        { id: uuid(), name: "per day" },
        { id: uuid(), name: "per week" },
        { id: uuid(), name: "per month" },
        { id: uuid(), name: "per year" },
    ],
    location: [
        { id: uuid(), name: "In person" },
        { id: uuid(), name: "Remote" },
        { id: uuid(), name: "On the road" },
    ],
    schedule: [
        { id: uuid(), name: "4x12" },
        { id: uuid(), name: "5x8" },
        { id: uuid(), name: "Monday to Friday" },
        { id: uuid(), name: "Day shift" },
        { id: uuid(), name: "Night shift" },
        { id: uuid(), name: "Evening shift" },
        { id: uuid(), name: "No nights" },
        { id: uuid(), name: "Overnight shift" },
        { id: uuid(), name: "Weekend availability" },
        { id: uuid(), name: "Weekends only" },
        { id: uuid(), name: "No weekends" },
        { id: uuid(), name: "On call" },
        { id: uuid(), name: "Holidays" },
        { id: uuid(), name: "Self-determined schedule" },
        { id: uuid(), name: "After school" },
        { id: uuid(), name: "Overtime" },
        { id: uuid(), name: "Other" },
    ],
    type: [
        { id: uuid(), name: "Full-time" },
        { id: uuid(), name: "Part-time" },
        { id: uuid(), name: "Contract" },
        { id: uuid(), name: "Temporary" },
        { id: uuid(), name: "Internship" },
        { id: uuid(), name: "Temp to perm" },
        { id: uuid(), name: "Zero hours contract" },
        { id: uuid(), name: "Volunteer" },
        { id: uuid(), name: "Apprenticeship" },
        { id: uuid(), name: "Graduate" },
    ],
    size: [
        { id: uuid(), name: "1" },
        { id: uuid(), name: "2" },
        { id: uuid(), name: "3" },
        { id: uuid(), name: "4" },
        { id: uuid(), name: "5" },
        { id: uuid(), name: "6" },
        { id: uuid(), name: "7" },
        { id: uuid(), name: "8" },
        { id: uuid(), name: "9" },
        { id: uuid(), name: "10" },
        { id: uuid(), name: "10+" },
        { id: uuid(), name: "I have an ongoing need to fill this role" },
    ],
    delay: [
        { id: uuid(), name: "1 to 3 days" },
        { id: uuid(), name: "3 to 7 days" },
        { id: uuid(), name: "1 to 2 weeks" },
        { id: uuid(), name: "2 to 4 weeks" },
        { id: uuid(), name: "More than 4 weeks" },
    ],
    payBy: [
        { id: uuid(), name: "Range" },
        { id: uuid(), name: "Starting amount" },
        { id: uuid(), name: "Maximum amount" },
        { id: uuid(), name: "Exact amount" },
    ],
    supplemental: [
        { id: uuid(), name: "Signing bonus" },
        { id: uuid(), name: "Tips" },
        { id: uuid(), name: "Commission pay" },
        { id: uuid(), name: "Bonus scheme" },
        { id: uuid(), name: "Loyalty bonus" },
        { id: uuid(), name: "Performance bonus" },
        { id: uuid(), name: "Yearly bonus" },
        { id: uuid(), name: "Safety Bonus" },
        { id: uuid(), name: "Quarterly bonus" },
        { id: uuid(), name: "Bonus pay" },
        { id: uuid(), name: "Tips" },
        { id: uuid(), name: "Other" },
    ],
    submitResume: [
        { id: uuid(), name: "Yes" },
        { id: uuid(), name: "No" },
        { id: uuid(), name: "Optional" },
    ],
    benefits: [
        { id: uuid(), name: "Health insurance" },
        { id: uuid(), name: "Paid time off" },
        { id: uuid(), name: "Dental insurance" },
        { id: uuid(), name: "401(k)" },
        { id: uuid(), name: "Vision insurance" },
        { id: uuid(), name: "Flexible schedule" },
        { id: uuid(), name: "Tuition reimbursement" },
        { id: uuid(), name: "Life insurance" },
        { id: uuid(), name: "401(k) matching" },
        { id: uuid(), name: "Retirement plan" },
        { id: uuid(), name: "Referral program" },
        { id: uuid(), name: "Employee discount" },
        { id: uuid(), name: "Flexible spending account" },
        { id: uuid(), name: "Health savings account" },
        { id: uuid(), name: "Relocation assistance" },
        { id: uuid(), name: "Parental leave" },
        { id: uuid(), name: "Professional development assistance" },
        { id: uuid(), name: "Employee assistance program" },
        { id: uuid(), name: "Other" },
    ],
    qualifications: [
        {
            id: uuid(),
            name: "Education",
            values: [
                { id: uuid(), name: "High school or equivalent" },
                { id: uuid(), name: "Associate" },
                { id: uuid(), name: "Bachelor's" },
                { id: uuid(), name: "Master's" },
                { id: uuid(), name: "Doctorate" },
            ],
        },
        {
            id: uuid(),
            name: "Experience",
            values: [
                { id: uuid(), name: "1 year" },
                { id: uuid(), name: "2 years" },
                { id: uuid(), name: "3 years" },
                { id: uuid(), name: "4 years" },
                { id: uuid(), name: "5 years" },
                { id: uuid(), name: "6 years" },
                { id: uuid(), name: "7 years" },
                { id: uuid(), name: "8 years" },
                { id: uuid(), name: "9 years" },
                { id: uuid(), name: "10 years" },
            ],
        },
        {
            id: uuid(),
            name: "Interview Ability",
            values: [],
        },
        {
            id: uuid(),
            name: "Security clearance",
            values: [
                { id: uuid(), name: "Confidential" },
                { id: uuid(), name: "Secret" },
                { id: uuid(), name: "Top Secret" },
            ],
        },
        {
            id: uuid(),
            name: "Shift Availability",
            values: [
                { id: uuid(), name: "Day Shift" },
                { id: uuid(), name: "Night Shift" },
                { id: uuid(), name: "Overnight Shift" },
            ],
        },
        {
            id: uuid(),
            name: "Skills test",
            values: [
                { id: uuid(), name: "Attention to detail" },
                { id: uuid(), name: "Software developer fit" },
                { id: uuid(), name: "Work style: Conscientiousness" },
                { id: uuid(), name: "Analyzing data" },
                { id: uuid(), name: "Learning agility" },
                { id: uuid(), name: "Work motivation" },
                { id: uuid(), name: "Graphic design" },
                { id: uuid(), name: "Work style: Reliability" },
                { id: uuid(), name: "Customer focus & orientation" },
                {
                    id: uuid(),
                    name: "Management & leadership skills: Impact & influence",
                },
                { id: uuid(), name: "Proofreading" },
                { id: uuid(), name: "Written communication" },
                { id: uuid(), name: "Technical support: Customer situations" },
                { id: uuid(), name: "Sales skills" },
                { id: uuid(), name: "Verbal communication" },
                { id: uuid(), name: "Technical support" },
                { id: uuid(), name: "Teamwork: Interpersonal skills" },
                { id: uuid(), name: "Typing" },
            ],
        },
        {
            id: uuid(),
            name: "Willingness to travel",
            values: [
                { id: uuid(), name: "25%" },
                { id: uuid(), name: "50%" },
                { id: uuid(), name: "75%" },
                { id: uuid(), name: "100%" },
            ],
        },
        {
            id: uuid(),
            name: "Work authorization",
            values: [],
        },
        {
            id: uuid(),
            name: "Create custom question",
            values: [],
        },
    ],
}
export default JOB
