import { FaArrowLeft, FaArrowRight } from "react-icons/fa"
import { v4 as uuid } from "uuid"

export const navbarNavigations = [
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Find jobs",
        slug: "jobs",
        href: "/",
        hrefMethod: () => router.push("/"),
        active: false,
        show: true,
        children: [],
        place: "top",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Companies reviews",
        slug: "companies",
        href: "/companies",
        hrefMethod: () => router.push("/companies"),
        active: false,
        show: true,
        children: [],
        place: "top",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Find Salaries",
        slug: "career-salaries",
        href: "/career/salaries",
        hrefMethod: () => router.push("/career/salaries"),
        active: false,
        show: true,
        children: [],
        place: "top",
    },
    // Right
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Profile",
        slug: "resume",
        href: "/resume",
        hrefMethod: () => router.push(`/resume`),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "My Jobs",
        slug: "saved",
        href: "/saved",
        hrefMethod: () => router.push("/saved"),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "My Reviews",
        slug: "contributions",
        href: "/contributions",
        hrefMethod: () => router.push("/contributions"),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "My demographics",
        slug: "reauthprompt",
        href: "/reauthprompt",
        hrefMethod: () => router.push("/reauthprompt"),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Settings",
        slug: "settings",
        href: "/settings",
        hrefMethod: () => router.push("/settings"),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Help Center",
        slug: "hc",
        href: "/hc",
        hrefMethod: () => router.push("/hc"),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowLeft,
        label: "Sign Out",
        slug: "auth-logout",
        href: "/auth/logout",
        hrefMethod: () => router.push("/auth/logout"),
        active: false,
        show: true,
        children: [],
        method: (e) => handelSignout(e),
        place: "right",
    },
]
